const newTypes = {
    CREATE_NEW_ACTION: "CREATE_NEW_ACTION",
    GET_LIST_NEW_ACTION: "GET_LIST_NEW_ACTION",
    GET_LIST_ALL_NEW_ACTION: "GET_LIST_ALL_NEW_ACTION",
    GET_DETAIL_NEW_ACTION: "GET_DETAIL_NEW_ACTION",
    UPDATE_NEW_ACTION: "UPDATE_NEW_ACTION",
    CREATE_NEW_SUCCESS: "CREATE_NEW_SUCCESS",
    GET_LIST_NEW_SUCCESS: "GET_LIST_NEW_SUCCESS",
    GET_LIST_ALL_NEW_SUCCESS: "GET_LIST_ALL_NEW_SUCCESS",
    GET_DETAIL_NEW_SUCCESS: "GET_DETAIL_NEW_SUCCESS",
    UPDATE_NEW_SUCCESS: "UPDATE_NEW_SUCCESS",
    CREATE_NEW_FAILED: "CREATE_NEW_FAILED",
    GET_LIST_ALL_NEW_FAILED: "GET_LIST_ALL_NEW_FAILED",
    GET_LIST_NEW_FAILED: "GET_LIST_NEW_FAILED",
    GET_DETAIL_NEW_FAILED: "GET_DETAIL_NEW_FAILED",
    UPDATE_NEW_FAILED: "UPDATE_NEW_FAILED",
    CLEAR_NEW_ACTION: "CLEAR_NEW_ACTION"
}

export default newTypes;