const orderTypes = {
    CHECKOUT_ORDER_ACTION: "CHECKOUT_ORDER_ACTION",
    CHECKOUT_ORDER_SUCCESS: "CHECKOUT_ORDER_SUCCESS",
    CHECKOUT_ORDER_FAILED: "CHECKOUT_ORDER_FAILED",
    PAYMENT_ORDER_ACTION: "PAYMENT_ORDER_ACTION",
    PAYMENT_ORDER_SUCCESS: "PAYMENT_ORDER_SUCCESS",
    PAYMENT_ORDER_FAILED: "PAYMENT_ORDER_FAILED",
    GET_ORDER_DETAIL_ACTION: "GET_ORDER_DETAIL_ACTION",
    GET_ORDER_DETAIL_SUCCESS: "GET_ORDER_DETAIL_SUCCESS",
    GET_ORDER_DETAIL_FAILED: "GET_ORDER_DETAIL_FAILED",
    GET_LIST_ODER_ACTION: "GET_LIST_ODER_ACTION",
    GET_LIST_ODER_SUCCESS: "GET_LIST_ODER_SUCCESS",
    GET_LIST_ODER_FAILED: "GET_LIST_ODER_FAILED",
    GET_ORDER_REVENUE_ACTION: "GET_ORDER_REVENUE_ACTION",
    GET_ORDER_REVENUE_SUCCESS: "GET_ORDER_REVENUE_SUCCESS",
    GET_ORDER_REVENUE_FAILED: "GET_ORDER_REVENUE_FAILED",
    UPDATE_ORDER_STATUS_ACTION: "UPDATE_ORDER_STATUS_ACTION",
    UPDATE_ORDER_STATUS_SUCCESS: "UPDATE_ORDER_STATUS_SUCCESS",
    UPDATE_ORDER_STATUS_FAILED: "UPDATE_ORDER_STATUS_FAILED",
    CLEAR_ORDER_ACTION: "CLEAR_ORDER_ACTION"
}

export default orderTypes;